### ISSUE TITLE
Use Sendmail instead of Gmail

### ISSUE THREAD

**Issue by rahul286** [RohiniPamarty/users_tasks#1]
For sending emails... Gmail is making your app slow!

**Comment by RohiniPamarty** [comment]
Have tried working with sendmail..but in development it is not working properly..can i use any gem if possible. Can you please guide on this issue if possible, how to deal with this.

**Comment by rahul286** [comment]
Which OS u r using for development?
U r free to use gems.

**Comment by RohiniPamarty** [comment]
i am working on Ubuntu OS and have tried installing sendmail and have sucessfully installed still i am unable to deliver mail. But in console it is displaying mail as sent. Can you please guide me the possible mistake i have done and how i need to proceed further.

**Comment by rahul286** [comment]
On Ubuntu you should not have a problem with sendmail. Please try again. You can use Google for some guidance.
Once you are done with this task, let me know.

**Comment by RohiniPamarty** [comment]
Have completed the required changes for sendmail.
