### ISSUE TITLE
Use Twitter Bootstrap

### ISSUE THREAD

**Issue by rahul286** [RohiniPamarty/users_tasks#3]
Please use Twitter Bootstrap http://twitter.github.com/bootstrap/
There are already few gems for Rails (which can save some work...)

This will make your application presentable.

**Comment by RohiniPamarty** [comment]
Have introduced Twitter bootstrap

**Comment by rahul286** [comment]
Good. Checked https://github.com/RohiniPamarty/users_tasks/tree/master/app/views/
