### ISSUE TITLE
Git specific

### ISSUE THREAD

**Issue by rahul286** [RohiniPamarty/users_tasks#5]
See - https://github.com/RohiniPamarty/users_tasks/tree/master/app/views/user_mailer
There are duplicate files ending with "~" in their name.

Ask git to ignore them. They are backup files and must not get committed to your repos.

**Comment by RohiniPamarty** [comment]
Have fixed this issue

**Comment by rahul286** [comment]
Verified this - https://github.com/RohiniPamarty/users_tasks/blob/master/.gitignore
